### ISSUE TITLE
vue3-chessboard for two player game - Assigning each player the color of white and black

### ISSUE THREAD

**Issue by LarsSjobom** [qwerty084/vue3-chessboard#168]
Hi,

I am trying to create an Online Chess Application with the vue3-chessboard. However I do not know how I can assign the movable attribute in the boardconfig to be reactive and change in accordance with which player is playing, right now both players can select both white and black pieces. I would like the players to only be able to select the players color. Please see row  74-90  in ChessGame.vue for the logic implemented. And row 38 for the initialization of the boardConfig. The console.logs in the logic 74-90 in ChessGame.vue are all printed correctly, but the 'movable' seem to be written over or not assigned. Please the provide code.

```html

<script setup>
/* eslint-disable */
import { ref, computed, onMounted, onUnmounted, nextTick } from 'vue';
import { useRoute } from 'vue-router';
import { TheChessboard } from 'vue3-chessboard';
import 'vue3-chessboard/style.css';
import { io } from 'socket.io-client';
import axios from 'axios';
import { watch } from 'vue';
import { reactive } from 'vue';

const socket = io('http://localhost:8080', {
  withCredentials: true,
});

const boardAPI = ref();

const route = useRoute();
const matchId = route.params.matchId;
const currentUser = localStorage.getItem('username');

async function fetchMatch(matchId) {
  try {
    const response = await axios.get(`http://localhost:8080/matches/${matchId}`);
    if (response.data.match) {
      match.value = response.data.match;
    }
  } catch (error) {
    console.error("Error fetching match:", error);
  }
}

const match = ref({
  white_player: '',
  black_player: '',
});

const boardConfig = ref({
  coordinates: false,
  autoCastle: false,
  movable: { color: null },
});

function handleMove({ from, to }) {
 // boardConfig = {...boardConfig, viewOnly: true }
 // const fen = boardAPI.value.getFen();
  // console.log(fen)
  socket.emit('move', { matchId, from, to});
}

function handleMoveError(error) {
  alert(error);
}

function handleCheckmateEvent({ winner }) {
  alert(`${winner} wins!`);
}

onMounted(async () => {
  await fetchMatch(matchId);

  socket.on(`move:${matchId}`, ({ from, to }) => {
    console.log(`Move received: ${from} -> ${to}`);
    boardAPI.value.move(from, to);
  });

  socket.on(`fenUpdate:${matchId}`, ({ fen }) => {
    console.log(`FEN Update received: ${fen}`);
    boardAPI.value.setPosition(fen);
    const whitePlayer = match.value.white_player;
    const turnColor = boardAPI.value ? boardAPI.value.getTurnColor() : null;

    if (turnColor === 'white' && currentUser === whitePlayer) {
      console.log("vit vit");
      nextTick(() => {
        boardConfig.value = { ...boardConfig.value, movable: { color: 'white' } };
      });
    } else if (turnColor === 'black' && currentUser !== whitePlayer) {
      console.log("svart vit");
      nextTick(() => {
        boardConfig.value = { ...boardConfig.value, movable: { color: 'black' } };
      });
    } else {
      console.log("viewOnly true");
      nextTick(() => {
        boardConfig.value = { ...boardConfig.value, movable: { color: null } };
      });
    }
  });

  socket.on('moveError', handleMoveError);

  socket.on('checkmate', handleCheckmateEvent);

  socket.on("matchUpdated", async (matchId) => {
  // Fetch the updated list of matches
  await fetchMatch(matchId);

});

});

onUnmounted(() => {
  socket.off(`move:${matchId}`);
  socket.off(`fenUpdate:${matchId}`);
  socket.off('moveError');
  socket.off('checkmate', handleCheckmateEvent);
  socket.disconnect();
});

</script>
<template>
  <main>
    <TheChessboard
      :key="JSON.stringify(boardConfig.value)"
      :board-config="boardConfig.value"
@board-created="(api) => (boardAPI = api)"
@move="handleMove"
/>

  </main>
</template>
\```

Appreciating any help I could get. 

Kind regards,
Lars

**Comment by bpem** [comment]
Hello !
Same issue here.

**Comment by antoinepemeja** [comment]
Hello,

If I setup the component `TheChessboard` with the fen `rnbqkbnr/ppp2ppp/3P4/8/8/8/PPP1PPPP/RNBQKBNR b KQkq - 0 3`, the function `boardAPI.value?.getTurnColor()` will return `white` instead of `black`.

Can you check in `TheChessboard.vue` -> `onMounted()`, maybe you have to set the correct `board.state.turnColor` depends to the fen injected.

**Comment by antoinepemeja** [comment]
Hello, 

My assumption, if you set up a board (with BoardConfig) to have only one color that is movable before the first move it will work. However, after the first move, the "changeTurn()" function in "TheChessboard.vue" will change this configuration. This allows to play on both sides.

**Comment by qwerty084** [comment]
Hey, thanks for your issue and the pr. I will look into this tomorrow.

**Comment by qwerty084** [comment]
The boardConfig prop is only read in the onMounted hook in the library, so at the moment there is no way to make it reactive.
But of course i could change that and apply the changes made to it or add a method to the board api to set the turn color.
But in theory you should not need to update the turn color manually after using setPosition, this should be done automatically.

Please try this config:
```ts
const boardConfig = {
  coordinates: false,
  autoCastle: false,
  movable: {
    free: false,
    color: undefined
  }
};
```

I think the problem is the board config merging. It thought/assumed this would also merge nested objects, but it doesnt...
```
boardState.value.boardConfig = {
      ...defaultBoardConfig,
      ...props.boardConfig,
};
```
I will release a new version today, which fixes the config merging. Please tell me if this fixes your issue.

**Comment by qwerty084** [comment]
sorry, didnt mean to close :D

**Comment by qwerty084** [comment]
Please try [1.1.6](https://www.npmjs.com/package/vue3-chessboard/v/1.1.6) release

**Comment by antoinepemeja** [comment]
Hello, thx for the patch. It doesn't solve the problem. Our need is to have a board that can only be played with its color. If I am the white player, at no time can I move the black pieces, I have to wait until it is my turn (depending on the FEN) to play my pieces. Maybe we are missing something in the use of your library, can you help us? Thanks a lot.

**Comment by qwerty084** [comment]
Ohh okay, sorry I mistunderstood your issue. Yeah this is not possible right now I think. I will check and add the feature if it isn’t.

**Comment by ddbogdanov** [comment]
Hello!

Ran into this issue while working on my own project and came up with a quick solution. Check PR #175

**Comment by qwerty084** [comment]
I will release a new version later today, which hopefully adds decent multiplayer support with [PR 175](https://github.com/qwerty084/vue3-chessboard/pull/175). Thanks to @ddbogdanov :)

**Comment by qwerty084** [comment]
Please try v1.1.7.
And set the new player-color prop on the board component.

For example:
```js
const playerColor = 'white';

...

<TheChessboard :player-color="playerColor" />

**Comment by antoinepemeja** [comment]
Hello @qwerty084 it works ! Thanks a lot
