### ISSUE TITLE
Selecting rook while castling breaks the game

### ISSUE THREAD

**Issue by caferelgin** [qwerty084/vue3-chessboard#178]
If a player castles by first selecting the king followed by rook, the game breaks. If empty square is selected instead of rook, the game continues as it should be. See screen recording below

**To Reproduce**
1. Get to a position when castling is available
2. Click on King
3. Click on Rook
4. The game breaks

**Expected behavior**
The game should continue without a problem.

**Screenshots**
![Screen Recording 2023-05-21 at 19 41 24](https://github.com/qwerty084/vue3-chessboard/assets/3657950/b5e3207b-dddc-4ac2-818a-de7bee9db9e6)

**Comment by qwerty084** [comment]
Thanks for your bug report. Which version are you using?

**Comment by qwerty084** [comment]
Should be fixed now. Thanks for the bug report.
