### ISSUE TITLE
Use the changeTurn method to make a move programmatically

### ISSUE THREAD

**Issue by Pepijnk12** [qwerty084/vue3-chessboard#18]
From the documentation it is not entirely clear how to make a move programmatically. 
Can the `changeTurn` method be used to do this?

Thank you for this amazing chess package. It really helps me to create my hobby chess analysis tool.
If you need any help to develop this package, please let me know.

**Comment by qwerty084** [comment]
Hey, 

thanks for your feedback!
The development and documentation is still in an early stage and far from finished.

You can use the move() function provided by the lichess playground to make a move on the board programmatically.

Example:

```typescript
function makeMove() {
  boardAPI.value?.board.move('e2', 'e4');  
  setTimeout(() => {  
    boardAPI.value?.board.move('e7', 'e5');  
  }, 1000);  
}
```

Any help in development would be very welcome :)

**Comment by qwerty084** [comment]
oh, youre right. Its out of sync :D

If you want you could implement a move method for the boardAPI which stays in sync with the board.
Or if you have any other idea for a feature let me know.

At the moment im mostly working on polishing the board, not really features.

**Comment by qwerty084** [comment]
i added a makeMove method in 0.0.7 ([8215b15](https://github.com/qwerty084/vue3-chessboard/commit/8215b152b11219e8764f4473959f5dd742f81123)).

Please reopen this issue if this method doesn't work for you or you see room for improvement.
