### ISSUE TITLE
Movable property on boardConfig is automatically true when playerColor prop is set.

### ISSUE THREAD

**Issue by ddbogdanov** [qwerty084/vue3-chessboard#180]
**Which version are you using**
1.1.7

**To Reproduce**
1. Pass playerColor prop as `'white'` or `'black'` into TheChessboard. 
2. Move any piece to any square on the chessboard. It will be moved regardless of whether or not the move is legal.

**Expected behavior**
Unless movable property is passed as true in the boardConfig prop, illegal moves should not be allowed to happen.

I believe I have a fix for this bug in mind, I will submit a pull request as soon as possible.

**Comment by ddbogdanov** [comment]
PR Suggestion #181 submitted.

**Comment by qwerty084** [comment]
Thanks!
