### ISSUE TITLE
Move event is not emitted in check, checkmate, stalemate, or draw.

### ISSUE THREAD

**Issue by ddbogdanov** [qwerty084/vue3-chessboard#182]
**Which version are you using**
1.1.7

**To Reproduce**
1. Move a piece into a position in which triggers a `check`, `checkmate` `stalemate` or `draw`
2. move event is not emitted

**Expected behavior**
Move event should be emitted on any move, regardless if it causes a check, checkmate, stalemate or draw. This is especially important in online multiplayer use.

**Comment by qwerty084** [comment]
Thanks for the bug report. emitBoardEvents() returns early on mate and checkmate. I will fix it later today.
