### ISSUE TITLE
How to acess the API

### ISSUE THREAD

**Issue by rmarabini** [qwerty084/vue3-chessboard#194]
Hi @qwerty084,

  Thanks for this nice vue.js component. I have installed it and executed a few examples. 

How can I access the API? In particular I am trying to use de method getMaterialCount() and save the result in a variable  but I do not understand how it works. So far I have tried the follwowing

```
<script setup>
import { ref } from 'vue';  //
import { TheChessboard } from 'vue3-chessboard';
import 'vue3-chessboard/style.css';

const boardAPI = ref();  //
const boardConfig = {
  coordinates: true,
  orientation: 'black',
   events: {
    move: (from, to, capture) => {
      // the move function fires after each move on the board, you can access the values from, to, and capture
      console.log(from, to, capture);
      console.log("boardApi", boardAPI.getMaterialCount());
      console.log("getMaterialCount", getMaterialCount());
    },
  },
};
</script>
```
Any help will be very welcomed 

     Thanks

**Comment by rmarabini** [comment]
Hi,

   I think I found a solution, Let me know if this is the way to go

//define the variable to use in the template
// https://vuejs.org/guide/essentials/template-refs.html
var materialCount2= ref(1);

// Define an async function with that calls the api function
async function getMaterialCountFunction() {
  materialCount2.value = await boardAPI.value?.getMaterialCount().materialDiff;
  console.log("materialDiff")
  console.log(materialCount2)
}

const boardConfig = {
  coordinates: true,
  orientation: 'black',
   events: {
    move: (from, to, capture) => {
      // the move function fires after each move on the board, you can access the values from, to, and capture
      console.log(from, to, capture);
      getMaterialCountFunction();
    },
  },
}

In the template just use

{{ materialCount2 }}

**Comment by qwerty084** [comment]
Hey, yes this works. After each move the value of materialCount2 will be updated and the change will be reflected in the dom.
But you don't need an async function for this method and you probably want to start with an initial value of 0 in materialCount2.

The problem in the first example is that you always need to use .value on the api, because its a reactive value.

```js
boardAPI.value?.getMaterialCount(); // .value to unwrap the reactive value, ? because it can be undefined.
```

[Vuejs Reactivity](https://vuejs.org/guide/essentials/reactivity-fundamentals.html)

**Comment by rmarabini** [comment]
Thanks for the help,

    I just summarize here the solution.

```
<script setup>
import { ref } from 'vue';  //
import { TheChessboard } from 'vue3-chessboard';
import 'vue3-chessboard/style.css';
var materialDiff= ref(0);   // this is a reactive variable, ref should be used
const boardAPI = ref();  

const boardConfig = {
  coordinates: true,
   events: {
    move: (from, to, capture) => {
      // the move function fires after each move on the board, you can access the values from, to, and capture
      console.log(from, to, capture);
      // assignation should be made to variable.value
      materialDiff.value = boardAPI.value?.getMaterialCount().materialDiff;
    },
  },
};

```

**Comment by qwerty084** [comment]
Looks good :)
