### ISSUE TITLE
Consider moving Vue to peerDependencies

### ISSUE THREAD

**Issue by benjaminpjones** [qwerty084/vue3-chessboard#197]
If an external library pulls in Vue, but Vue is already included in the project, [it causes issues](https://github.com/vuejs/core/issues/2913).

Consider moving `vue` from `dependencies` (see [package.json](https://github.com/qwerty084/vue3-chessboard/blob/main/package.json#L59)) to [`peerDependencies`](https://nodejs.org/en/blog/npm/peer-dependencies).

**Comment by qwerty084** [comment]
Thanks. I will look into this. I think it’s somewhat handled by [Vite library mode](https://vitejs.dev/guide/build.html#library-mode).
Vue is declared as an external dependency which should not be bundled in vite config. But you’re right. Dev- or peerDependency is probably better.
