### ISSUE TITLE
Event for user drawing?

### ISSUE THREAD

**Issue by bradintheusa** [qwerty084/vue3-chessboard#207]
Hi,

The user can draw arrows on the board. Is there an event for this? I want to know when they have drawn or cleared an arrow.

Thanks

**Comment by qwerty084** [comment]
Hey,

yes, you can use the chessground `onChange` callback of the `drawable` property:

```ts
const boardConfig: BoardConfig = {
  drawable: {
    onChange: (drawable) => {
      console.log(drawable);
    },
  },
};
```

Example output:
```json
[
    {
        "orig": "e2",
        "dest": "e5",
        "brush": "green"
    },
    {
        "orig": "d2",
        "brush": "green"
    }
]
```

**Comment by bradintheusa** [comment]
Works perfectly thanks
