### ISSUE TITLE
testing with cypress

### ISSUE THREAD

**Issue by rmarabini** [qwerty084/vue3-chessboard#218]
I have written an application that uses  vue3-chessboard. 

As you know, if the user right clicks on a square of the chessboard a circle should appear around the selected piece. I want to write a test that simulates clicks on different pieces

I have written many variations of the following script to simulate a right-click (the script assumes that the testing tool cypress has been installed -https://docs.cypress.io-)

describe('Click Test', () => {
    it('clicking', () => {
      cy.visit('https://qwerty084.github.io/vue3-chessboard/')
      cy.url().should('include', 'http');
      // wait a second just in case
      cy.wait(1000);
      // click on the piece in the 4th position
      cy.get('piece').eq(4).rightclick({ force: true });
      // click on the piece in the 20th position
      cy.get('piece').eq(20).rightclick({ force: true });
   });
})

but unfortunately the script does not work.

After the test execution if I hover over the last executed line: "-rightclick(force=True)" a little red sphere appears on the chessboard on the right coordinates so the element is found and the rightclick command is executed but not circle appears.

Any help with this problem will be welcomed.

**Comment by qwerty084** [comment]
Hey,

lichess chessground doesn't allow clicks from scripts such as cypress (https://github.com/lichess-org/chessground/issues/267).
I've never used cypress before, maybe there is a way to get it work, idk sorry.

**Comment by rmarabini** [comment]
Hi @qwerty084,

    Thanks for the tip I will further investigate.

**Comment by rmarabini** [comment]
hi @qwerty084,

   It seems that is possible to use cypress tests if the parameter 

  trustAllEvents:true,

is passed to chessground when a new instance is created. 

Could you tell me how to modify your code to add this parameter?

   Thanks

**Comment by rmarabini** [comment]
hi @qwerty084 ,

  I see that   trustAllEvents parameter was added a couple of months ago  and it is not present in the chessground version distributed with vue3-chessboard :-(

**Comment by qwerty084** [comment]
I updated chessground to the latest version and released a new version. Please update to v1.2.2


In the boardConfig you can then set trustAllEvents.

**Comment by rmarabini** [comment]
Hi @qwerty084,

   Now the tests work. I almost cried when I saw the pieces moving. Thanks for your help.
In case somebody want to use cypress

      cy.get('cg-board')
      .click(x0, y0)
      .click(x1, y1)

will move a piece from the square center on (x0, y0) to the square centered t (x1, y1).  github user trufa has nice examples of complex test in the repository https://github.com/trufa/opening.expert/tree/main/cypress. 

Do not forget to set trustAllEvents to true
