### ISSUE TITLE
Error resetting board during incomplete move of a black piece

### ISSUE THREAD

**Issue by thomaskrut** [qwerty084/vue3-chessboard#220]
**Description**
Resetting the board by calling resetBoard() on the API causes an exception (Uncaught TypeError: t.get is not a function) when the following conditions are true:
- Orientation is set to 'black'
- The user has selected a piece to be moved, but has not yet selected a destination square. That is, the piece is not dragged and dropped, but rather moved using the two clicks approach

**Version**
1.2.2

**To Reproduce**
Use Vue component:
```
<script setup>
import { TheChessboard } from 'vue3-chessboard';
import 'vue3-chessboard/style.css';
let boardAPI;
const boardConfig = {
  orientation: 'black',
}
</script>
<template>
  <TheChessboard :board-config="boardConfig" @board-created="(api) => (boardAPI = api)"/>
  <button @click="boardAPI.resetBoard()">Reset board</button>
</template>

```
1. Move a white piece
2. Click any black piece (don't move it)
3. Click the "reset board" button

This causes a crash.

**Comment by qwerty084** [comment]
Hey, thanks for your bug report. Please try v1.2.3. It should fix the described bug.

**Comment by thomaskrut** [comment]
Thank you, it seems to be working. My workaround was truly terrible, so this helps alot. I'm working on a chess openings trainer based on your component and the lichess API.

**Comment by qwerty084** [comment]
Great to hear. I just checked out your project, nice work! :)
