### ISSUE TITLE
How to add stockfish.js AI

### ISSUE THREAD

**Issue by zafarich** [qwerty084/vue3-chessboard#229]
I add vue3-chessboard. Component works correctly. But I need to add stockfish AI

**Comment by qwerty084** [comment]
Hey, you need to add [stockfish.js](https://github.com/lichess-org/stockfish.js) for example to your project. Then read the engine output and use `drawMove` and/or `move` method from the api to indicate the best move. I will add an example to the documentation, probably this weekend.

**Comment by zafarich** [comment]
Thanks bro. It would be great if you could show an example of how to use it. For an example that selects game levels

**Comment by zafarich** [comment]
If you add an example, write it here. please

**Comment by qwerty084** [comment]
> Thanks bro. It would be great if you could show an example of how to use it. For an example that selects game levels

Not sure what you mean by game levels?

My idea was to explain the general usage and add an example where you play vs Stockfish.

**Comment by zafarich** [comment]
It is true. I need to add an example where you play vs Stockfish

**Comment by qwerty084** [comment]
Hi, the documentation for uci engines (stockfish) is almost ready. I will finish it tomorrow.
Here is the current state maybe it can help you, but be careful its wip... 
https://github.com/qwerty084/vue3-chessboard-docs/blob/main/src/stockfish.md

**Comment by qwerty084** [comment]
New documentation is now live.
You can find the stockfish example here: https://qwerty084.github.io/vue3-chessboard-docs/stockfish.html

**Comment by larskuerten** [comment]
The Engine.js has public and private modifiers
The css is missing in the Vue component

Fixing this it works as expected
