### ISSUE TITLE
Promotion widget wrongly placed when multiple chessboards are used

### ISSUE THREAD

**Issue by mouaip** [qwerty084/vue3-chessboard#230]
Hi !

First thing first: thanks for the work ! I was nearly ready to do the integration of vue/chessboard/chessjs myself (it would have been poorer) when I found your project: a life saver.

**Describe the bug**
When there is several chessboard instances on the same page, and when there is a promotion, the dialog for the piece selection is set on the first chessboard.

**Which version are you using**
I'm using the last official release.

**To Reproduce**
Easy to see it: there is several chessboards on this page https://qwerty084.github.io/vue3-chessboard/props.html.
So you just have to go to promotion on the one at the bottom of the page and you will see that the widget for the piece selecting  is set on the first chessboard.

**Comment by qwerty084** [comment]
Hey, thanks for your bug report. I will fix it this weekend.

**Comment by zafarich** [comment]
Move with promotion error has been
