### ISSUE TITLE
Castling is not possible. The King get stuck and the rook don't move. 

### ISSUE THREAD

**Issue by Awazez** [qwerty084/vue3-chessboard#253]
**Describe the bug**
Castling is impossible. The king get stuck on g1 for the white for example. 

**Which version are you using**
v1.3.3

**To Reproduce**

initialPos = 'rnbqk2r/pppp1ppp/5n2/2b1p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 0 1';

1. Go to to the initalposition propose before 
2. Click on the king and try to castling. 

**Expected behavior**
The king should castling correctly. 

**Screenshots**

![Capture d’écran 2024-05-07 à 3 13 37 PM](https://github.com/qwerty084/vue3-chessboard/assets/51866468/f1bc4e7f-f266-42f5-b93b-f0443c39b09d)

**Comment by PawelGawlikDev** [comment]
Setting `autoCastle: true` should solve this issue

**Comment by qwerty084** [comment]
Yes `autoCastle: true` should fix it. Thanks @PawelGawlikDev.
Its removed in #256.
I will close this issue. If autoCastle doesn't work for you, please reopen.
