### ISSUE TITLE
OnMove method?

### ISSUE THREAD

**Issue by fabthegreat** [qwerty084/vue3-chessboard#47]
Hi, great job!
Is there a way to retrieve a move (whatever the format) once it has been played?

Thanks

**Comment by qwerty084** [comment]
Hey,

you could register a afterMoveCallback function and then get the last move from the lichess chessground.

```html
<script setup lang="ts">
import { ref, toRaw } from 'vue';
import { TheChessboard, type ChessboardAPI, type BoardConfig } from '@/index';
import '@/assets/board.css';
const boardAPI = ref<ChessboardAPI>();

async function afterMove() {
  console.log(toRaw(boardAPI.value?.board.state.lastMove));
}

const boardConfig: BoardConfig = {
  coordinates: true,
  autoCastle: false,
};
</script>

<template>
  <main>
    <section>
      <button type="button" @click="boardAPI?.board.toggleOrientation()">
        Toggle orientation
      </button>
      <button type="button" @click="boardAPI?.resetBoard()">Reset</button>
      <button type="button" @click="boardAPI?.undoLastMove()">Undo</button>
      <button type="button" @click="boardAPI?.toggleThreats()">Threats</button>
    </section>
    <TheChessboard
      :board-config="boardConfig"
      :after-move-cb="afterMove"
      @board-created="(api) => (boardAPI = api)"
    />
  </main>
</template>
```

Output:
```js
Array [ "e2", "e4" ]
```

Please let me know if this works for you.

I will probably add some more methods to the boardapi in the next version, including a method to get the last move easier and with more information.

**Comment by fabthegreat** [comment]
Thanks for your answer! I finally coded my chessboard from scratch ;) but it is far less good looking than yours for the moment! For now my main concern is about the possible moves on the board, it works based on chessjs lib but it takes a huge amount of time (something like 180ms for a Queen with many possible moves). It is related to the chessjs lib itself, maybe I'll give a try with another one.

**Comment by qwerty084** [comment]
I also use chess.js to generate the possibles moves. Its working fine.

Im going to close this for now...
